/*
 * Copyright 2026 Gagik Sargsyan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.ketraterm.completion.api

import java.text.MessageFormat
import java.util.*

/**
 * Host message lookup for descriptions generated by reusable completion sources.
 *
 * Hosts may delegate to their existing bundle facade. Keys and complete patterns
 * are defined in `io.github.ketraterm.completion.api.CompletionMessages`.
 * Static descriptions are read during source/engine construction. Lookup
 * implementations must be thread-safe because requests may run concurrently.
 * Provider-owned descriptions and canonical insertion tokens are unchanged.
 */
public fun interface TerminalCompletionMessages {
    /** Returns [key], formatting its complete pattern with [arguments] when supplied. */
    public fun message(
        key: String,
        vararg arguments: Any,
    ): String

    public companion object {
        /** Creates a UTF-8 resource-bundle lookup with English fallback and thread-safe [MessageFormat] patterns. */
        @JvmStatic
        @JvmOverloads
        public fun forLocale(
            locale: Locale = Locale.getDefault(Locale.Category.DISPLAY),
            bundle: ResourceBundle =
                ResourceBundle.getBundle(
                    "io.github.ketraterm.completion.api.CompletionMessages",
                    locale,
                    ResourceBundle.Control.getNoFallbackControl(ResourceBundle.Control.FORMAT_PROPERTIES),
                ),
        ): TerminalCompletionMessages {
            val fallback = ResourceBundle.getBundle("io.github.ketraterm.completion.api.CompletionMessages", Locale.ROOT)
            return TerminalCompletionMessages { key, arguments ->
                val pattern = if (bundle.containsKey(key)) bundle.getString(key) else fallback.getString(key)
                if (arguments.isEmpty()) pattern else MessageFormat(pattern, locale).format(arguments)
            }
        }
    }
}
