/*
 * Copyright 2026 Gagik Sargsyan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {parseHTML} from "linkedom";

const root = fileURLToPath(new URL("../../build/website/", import.meta.url));
const pages = [];
for (const name of fs.readdirSync(root))
  if (name.endsWith(".html")) pages.push(path.join(root, name));
// API trees are generated by Dokka. Check site pages and all Markdown guides.
function visitGuides(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) visitGuides(file);
    else if (entry.isFile() && entry.name.endsWith(".html")) pages.push(file);
  }
}
for (const name of fs.readdirSync(path.join(root, "library")))
  if (name.endsWith(".html")) pages.push(path.join(root, "library", name));
visitGuides(path.join(root, "library/guides"));
visitGuides(path.join(root, "guides"));
const documents = new Map(
  pages.map((file) => [
    file,
    parseHTML(fs.readFileSync(file, "utf8")).document,
  ]),
);
const errors = [];
for (const [file, document] of documents) {
  const links = [...document.querySelectorAll("[href],[src]")].map(
    (element) => element.getAttribute("href") ?? element.getAttribute("src"),
  );
  for (const map of document.querySelectorAll('script[type="importmap"]'))
    links.push(...Object.values(JSON.parse(map.textContent).imports));
  for (const link of links) {
    if (!link || /^(?:[a-z][\w+.-]*:|\/\/)/i.test(link)) continue;
    const [pathname, fragment] = link.split("#");
    let target = pathname
      ? path.resolve(
          path.dirname(file),
          decodeURIComponent(pathname.split("?")[0]),
        )
      : file;
    if (fs.existsSync(target) && fs.statSync(target).isDirectory())
      target = path.join(target, "index.html");
    if (!target.startsWith(root) || !fs.existsSync(target))
      errors.push(`${path.relative(root, file)}: missing ${link}`);
    else if (
      file.startsWith(path.join(root, "library") + path.sep) &&
      !target.startsWith(path.join(root, "library") + path.sep)
    )
      errors.push(
        `${path.relative(root, file)}: library depends on parent site: ${link}`,
      );
    else if (
      fragment &&
      documents.has(target) &&
      !documents.get(target).getElementById(decodeURIComponent(fragment))
    )
      errors.push(`${path.relative(root, file)}: missing anchor ${link}`);
  }
}
if (errors.length) {
  console.error(errors.join("\n"));
  process.exitCode = 1;
} else
  console.log(
    `Checked local links and anchors in ${documents.size} website and guide pages.`,
  );
