/*
 * Copyright 2026 Gagik Sargsyan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.ketraterm.host

/**
 * Host-facing security policy for terminal controls that can affect host state,
 * retain host metadata, or write terminal-generated bytes back to the remote
 * process.
 *
 * The parser only recognizes protocols. This policy is evaluated in the host
 * adapter before commands touch core state, host callbacks, metadata registries,
 * or terminal-to-host response queues.
 *
 * @property titlePolicy origin-aware policy for OSC title updates and
 * title-stack restore operations before adapter/core title metadata changes or
 * host callbacks are emitted.
 * @property hyperlinkPolicy whether OSC 8 hyperlinks may be retained and
 * attached to written cells.
 * @property currentWorkingDirectoryPolicy whether OSC 7 current-working-directory
 * reports may be retained and forwarded to the host.
 * @property notificationPolicy whether terminal-triggered desktop notification
 * requests may be forwarded to the host.
 * @property windowManipulationPolicy whether terminal-triggered window movement,
 * resize, minimize, raise, lower, and maximize requests may be forwarded.
 * @property palettePolicy whether OSC palette updates and palette query
 * responses may affect core palette state or enqueue terminal-to-host bytes.
 * @property terminalResponsePolicy whether DA, DSR/CPR, window reports, DECRQCRA,
 * DECRQSS, and XTGETTCAP requests may enqueue terminal-to-host response bytes.
 * @property clipboardPolicy deny-by-default permission and audit policy for
 * terminal-triggered clipboard protocols such as OSC 52.
 * @property maxHyperlinkEntries maximum distinct OSC 8 hyperlink keys retained
 * by the adapter before least-recently-used entries are evicted.
 * @property maxHyperlinkUriLength maximum accepted OSC 8 URI length in UTF-16
 * code units. Longer URIs are ignored and mapped to no active hyperlink.
 * @property maxHyperlinkIdLength maximum accepted OSC 8 `id=` parameter length
 * in UTF-16 code units. Longer IDs are ignored and mapped to no active
 * hyperlink.
 * @property maxNotificationTitleLength maximum accepted character length for
 * desktop notification titles.
 * @property maxNotificationBodyLength maximum accepted character length for
 * desktop notification bodies.
 * @property maxCurrentWorkingDirectoryUriLength maximum accepted OSC 7 file URI
 * length in UTF-16 code units. Longer or malformed URIs are ignored.
 */
data class HostPolicy(
    val titlePolicy: TerminalTitlePolicy = TerminalTitlePolicy(),
    val hyperlinkPolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val currentWorkingDirectoryPolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val notificationPolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val windowManipulationPolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val palettePolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val terminalResponsePolicy: HostControlPolicy = HostControlPolicy.ALLOW,
    val clipboardPolicy: TerminalClipboardPolicy = TerminalClipboardPolicy(),
    val maxHyperlinkEntries: Int = 4096,
    val maxHyperlinkUriLength: Int = 4096,
    val maxHyperlinkIdLength: Int = 256,
    val maxNotificationTitleLength: Int = 256,
    val maxNotificationBodyLength: Int = 1024,
    val maxCurrentWorkingDirectoryUriLength: Int = 4096,
) {
    init {
        require(maxHyperlinkEntries > 0) {
            "maxHyperlinkEntries must be positive, got $maxHyperlinkEntries"
        }
        require(maxHyperlinkUriLength >= 0) {
            "maxHyperlinkUriLength must be non-negative, got $maxHyperlinkUriLength"
        }
        require(maxHyperlinkIdLength >= 0) {
            "maxHyperlinkIdLength must be non-negative, got $maxHyperlinkIdLength"
        }
        require(maxNotificationTitleLength >= 0) {
            "maxNotificationTitleLength must be non-negative, got $maxNotificationTitleLength"
        }
        require(maxNotificationBodyLength >= 0) {
            "maxNotificationBodyLength must be non-negative, got $maxNotificationBodyLength"
        }
        require(maxCurrentWorkingDirectoryUriLength >= 0) {
            "maxCurrentWorkingDirectoryUriLength must be non-negative, got $maxCurrentWorkingDirectoryUriLength"
        }
    }
}

/**
 * Binary decision for host-affecting terminal controls.
 *
 * Policy decisions are intentionally explicit instead of inferred from size
 * limits. A denied family is ignored before it mutates metadata or emits host
 * callbacks, even when payload lengths are otherwise valid.
 */
enum class HostControlPolicy {
    /**
     * Ignore the terminal control family at the host adapter boundary.
     */
    DENY,

    /**
     * Accept the terminal control family subject to protocol-specific bounds.
     */
    ALLOW,
}
